name: sync table to rime yi repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # Checks-out rime-yi repo
      - name: Checkout rime-yi repo
        uses: actions/checkout@v4
        with:
          repository: lakent/rime-yi
          path: rime-yi
          token: ${{ secrets.REPOTOKEN }}
           
      - name: merge dict
        run: |
          cat rime-yi/yi_dict_header.yaml yi_table.txt > rime-yi/yi.dict.yaml

      - name: merge opencc
        run: |
          paste yi_table.txt yi_spelling.txt | awk '{print $1"\t"$2"·"$4}' > rime-yi/opencc/yi_spelling.txt
          
      - name: Push to rime-yi
        run: |
          cd rime-yi
          git config user.name  ${{ secrets.GITUSERNAME }}
          git config user.email ${{ secrets.GITUSEREMAIL }}
          git add yi.dict.yaml
          git add opencc/yi_spelling.txt
          git commit -m "sync rime yi"
          git push
